language: csharp
dotnet: 2.1.402
mono: none
before_install:
  - openssl aes-256-cbc -K $encrypted_e51b289ed3f5_key -iv $encrypted_e51b289ed3f5_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
script:
  - ./build.sh ci